import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/app/(layout)/footer";
import { Navbar } from "@/app/(layout)/navbar";
import { QueryProvider } from "@/app/(layout)/query-provider";
import { ThemeProvider } from "@/app/(layout)/theme-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider>
					<QueryProvider>
						<div className="min-h-screen flex flex-col">
							<Navbar />
							<main className="flex-1 container py-8 px-4 mx-auto">
								{children}
							</main>
						</div>
						<Footer />
					</QueryProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
